# "name","scipy_name","lower_limit","upper_limit

candidates = [
	("alpha","alpha",True,False),
	("anglit","anglit",True,True),
	("arcsine","arcsine",True,True),
	("argus","argus",True,True),
	("Beta","beta",True,True),
	("Beta Prime","betaprime",True,False),
	("Bradford","bradford",True,True),
	("Burr","burr",True,False),
	("Burr Type XII","burr12",True,False),
	("Cauchy","cauchy",False,False),
	("Chi","chi",True,False),
	("Chi^2","chi2",True,False),
	("Cosine","cosine",True,True),
	("Crystal Ball","crystalball",False,False),
	("Double Gamma","dgamma",False,False),
	("Double Pareto Lognormal","dpareto_lognorm",True,False),
	("Double Weibull","dweibull",False,False),
	("Erlang","erlang",True,False),
	("Exponential","expon",True,False),
	("Exponentially Modified Normal","exponnorm",False,False),
	("Exponentiated Weibull","exponweib",True,False),
	("Exponential Power","exponpow",True,False),
	("F","f",True,False),
	("Fatigue Life","fatiguelife",True,False),
	("Fisk","fisk",True,False),
	("Folded Cauchy","foldcauchy",True,False),
	("Folded Normal","foldnorm",True,False),
	("Generalized Logistic","genlogistic",False,False),
	("Generalized Normal","gennorm",False,False),
	("Generalized Pareto","genpareto",True,False),
	("Generalized Pareto","genpareto",True,True),
	("Generalized Exponential","genexpon",True,False),
	("Generalized Extreme Value","genextreme",True,True),
	("Generalized Extreme Value","genextreme",True,True),
	("Generalized Extreme Value","genextreme",True,True),
	("Gauss Hypergeometric","gausshyper",True,True),
	("Gamma","gamma",True,False),
	("Generalized Gamma","gengamma",True,False),
	("Generalized Half-Logistic","genhalflogistic",True,True),
	("Generalized Hyperbolic","genhyperbolic",False,False),
	("Generalized Inverse Gaussian","geninvgauss",True,False),
	("Gibrat","gibrat",True,False),
	("Gompertz","gompertz",True,False),
	("Gumbel Right-skewed","gumbel_r",False,False),
	("Gumbel Left-skewed","gumbel_l",False,False),
	("Half-Cauchy","halfcauchy",True,False),
	("Half-Logistic","halflogistic",True,False),
	("Half-Normal","halfnorm",True,False),
	("Half Generalized Normal","halfgennorm",True,False),
	("Hyperbolic Secant","hypsecant",False,False),
	("Inverse Gamma","invgamma",True,False),
	("Inverse Gaussian","invgauss",True,False),
	("Inverse Weibull","invweibull",True,False),
	("Irwin-Hall","irwinhall",True,True),
	("Jones and Faddy Skew-T","jf_skew_t",False,False),
	("Johnson's S<sub>B</sub>","johnsonsb",True,True),
	("Johnson's S<sub>U</sub>","johnsonsu",False,False),
	("Four-parameter Kappa","kappa4",False,False),
	("Three-Parameter Kappa Distribution","kappa3",True,False),
	("Kolmogorov-Smirnov one-sided test statistic distribution","ksone",True,True),
	("Kolmogorov-Smirnov two-sided test statistic distribution","kstwo",True,True),
	("Limiting distribution of scaled Kolmogorov-Smirnov two-sided test statistic","kstwobign",True,False),
	("Landau","landau",False,False),
	("Laplace","laplace",False,False),
	("Asymmetric Laplace","laplace_asymmetric",False,False),
	("Lévy","levy",True,False),
	("Left-skewed Lévy","levy_l",False,True),
	("Lévy stable","levy_stable",False,False),
	("Logistic","logistic",False,False),
	("Log-gamma","loggamma",False,False),
	("Log-Laplace","loglaplace",True,False),
	("Log-normal","lognorm",True,False),
	("Log-uniform","loguniform",True,True),
	("Lomax","lomax",True,False),
	("Maxwell","maxwell",True,False),
	("Mielke's Beta-Kappa","mielke",True,False),
	("Moyal","moyal",False,False),
	("Nakagami","nakagami",True,False),
	("Noncentral $\chi^2$","ncx2",True,False),
	("Noncentral *F*-distribution","ncf",True,False),
	("Noncentral Student’s *t*-distribution","nct",False,False),
	("Normal","norm",False,False),
	("Normal inverse Gaussian","norminvgauss",False,False),
	("Pareto","pareto",True,False),
	("Pearson Type III","pearson3",False,False),
	("Power-function","powerlaw",True,True),
	("Power log-normal","powerlognorm",True,False),
	("Power normal","powernorm",False,False),
	("symmetric beta","rdist",True,True),
	("Rayleigh","rayleigh",True,False),
	("Relativistic Breit–Wigner","rel_breitwigner",True,False),
	("Rice","rice",True,False),
	("Reciprocal inverse Gaussian","recipinvgauss",True,False),
	("Semicircular","semicircular",True,True),
	("Skewed Cauchy","skewcauchy",False,False),
	("Skew-normal","skewnorm",False,False),
	("Studentized range","studentized_range",True,False),
	("Student's *t*","t",False,False),
	("Trapezoidal","trapezoid",True,True),
	("Triangular","triang",True,True),
	("Truncated exponential","truncexpon",True,True),
	("Truncated normal","truncnorm",True,True),
	("Truncated Pareto","truncpareto",True,True),
	("Truncated Weibull minimum","truncweibull_min",True,True),
	("Tukey lambda","tukeylambda",True,True),
	("Uniform","uniform",True,True),
	("Von Mises","vonmises",True,True),
	("Von Mises","vonmises_line",True,True),
	("Wald","wald",True,False),
	("Weibull Minimum Extreme Value","weibull_min",True,False),
	("Weibull Maximum Extreme Value","weibull_max",False,True),
	("Wrapped Cauchy","wrapcauchy",True,True),
]